separated displacements management in omp version

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -18,7 +18,6 @@
 EXE:=circles
 CFLAGS=-std=c99 -Wall -Wpedantic
 LDLIBS+=-lm
-#
 OMP-FLAGS:=-fopenmp
 OMP-EXE:=omp-circles
 CUDA-EXE:=cuda-circles
@@ -26,7 +25,6 @@ GEN-EXE:=gen-circles
 
 
 ALL: $(EXE) $(OMP-EXE) $(CUDA-EXE) $(GEN-EXE)
-#
 
 $(EXE).movie: CFLAGS+=-DMOVIE
 $(EXE).movie: $(EXE).c
@@ -37,31 +35,31 @@ movie: $(EXE).movie
 	for f in *.gp; do echo "Processing $$f"; gnuplot "$$f"; done
 	ffmpeg -y -i "circles-%05d.png" -vcodec mpeg4 circles.avi
 
-#
 $(OMP-EXE): CFLAGS+=$(OMP-FLAGS)
-
-omp-dbg: CFLAGS+=-DDBG $(OMP-FLAGS)
-omp-dbg: $(OMP-EXE).c
+$(OMP-EXE): $(OMP-EXE).c
 	$(CC) $(CFLAGS) $< -o $@ $(LDLIBS)
 
-serial-dbg: CFLAGS+=-DDBG
-serial-dbg: $(EXE).c
-	$(CC) $(CFLAGS) $< -o $@ $(LDLIBS)
+# omp-dbg: CFLAGS+=-DDBG $(OMP-FLAGS)
+# omp-dbg: $(OMP-EXE).c
+# 	$(CC) $(CFLAGS) $< -o $@ $(LDLIBS)
 
-omp-test: serial-dbg omp-dbg $(GEN-EXE)	
-	for i in $$(seq 1 1) ; do \
-		./$(GEN-EXE) 10000; \
-		./serial-dbg > res_serial_time.txt ; \
-		./omp-dbg > res_omp_time.txt ; \
-		sed 's/([^)]*)//' res_serial_time.txt | head -n -1 > res_serial.txt ; \
-		sed 's/([^)]*)//' res_omp_time.txt | head -n -1 > res_omp.txt ; \
-		if ! cmp -s res_serial.txt res_omp.txt ; then \
-			echo "Errore: I file di output per l'iterazione $${i} sono diversi." ; \
-		exit 1; \
-		fi; \
-		echo "Iterazione $${i} OK"; \
-	done
+# serial-dbg: CFLAGS+=-DDBG
+# serial-dbg: $(EXE).c
+# 	$(CC) $(CFLAGS) $< -o $@ $(LDLIBS)
+# 
+# omp-test: serial-dbg omp-dbg $(GEN-EXE)	
+# 	for i in $$(seq 1 1) ; do \
+# 		./$(GEN-EXE) 10000; \
+# 		./serial-dbg > res_serial_time.txt ; \
+# 		./omp-dbg > res_omp_time.txt ; \
+# 		sed 's/([^)]*)//' res_serial_time.txt | head -n -1 > res_serial.txt ; \
+# 		sed 's/([^)]*)//' res_omp_time.txt | head -n -1 > res_omp.txt ; \
+# 		if ! cmp -s res_serial.txt res_omp.txt ; then \
+# 			echo "Errore: I file di output per l'iterazione $${i} sono diversi." ; \
+# 		exit 1; \
+# 		fi; \
+# 		echo "Iterazione $${i} OK"; \
+# 	done
 
 clean:
 	\rm -f $(EXE) $(EXE).movie $(OMP-EXE) $(CUDA-EXE) $(GEN-EXE) serial-dbg omp-dbg cuda-dbg *.txt *.o *~ *.gp *.png *.avi 
-# 
